"""Configuration management using Pydantic."""

import configparser
import io
import re
from pathlib import Path
from typing import Optional

from pydantic import BaseModel, Field, field_validator

from output import error


class ZilchConfig(BaseModel):
    """Configuration for Zilch GCP deployment."""

    # Core settings
    gcp_project_id: str
    app_name: str
    gcp_region: str = "us-central1"

    # Phase 1: Basic services
    enable_firestore: bool = False
    enable_secret_manager: bool = False
    enable_cloud_storage: bool = False
    enable_firebase_auth: bool = False
    enable_vertex_ai: bool = False

    # Phase 2: Cloud Build + GitOps
    enable_cloud_build: bool = True

    # Phase 3: Advanced services
    enable_pubsub: bool = False
    enable_cloud_tasks: bool = False
    enable_bigquery: bool = False
    enable_cloud_kms: bool = False
    enable_vision_ai: bool = False
    enable_speech_to_text: bool = False
    enable_translation: bool = False

    # Phase 4: Scheduler & Monitoring
    enable_scheduler: bool = False
    scheduler_schedule: str = "0 0 * * *"
    scheduler_timezone: str = "UTC"
    scheduler_endpoint: str = "/api/cron"
    enable_monitoring: bool = False
    billing_account_name: str = "My Billing Account"
    billing_budget_limit_usd: str = "10"

    # Phase 5: MySQL
    enable_mysql: bool = False
    mysql_database_name: str = "zilch_app"

    # Access control & billing
    allow_unauthenticated_access: bool = True
    gcp_billing_account_id: Optional[str] = None

    # GitHub integration (Cloud Build)
    github_owner: Optional[str] = None
    github_repo: Optional[str] = None

    model_config = {"extra": "ignore"}  # Ignore unknown fields

    @field_validator("app_name")
    @classmethod
    def validate_app_name(cls, v: str) -> str:
        """Validate app name format: 3-30 lowercase letters, numbers, hyphens."""
        if not re.match(r"^[a-z0-9-]{3,30}$", v):
            raise ValueError(
                "Invalid app name: must be 3-30 lowercase letters/numbers/hyphens"
            )
        return v

    @field_validator("gcp_region")
    @classmethod
    def validate_region(cls, v: str) -> str:
        """Validate GCP region."""
        valid_regions = ["us-central1", "us-east1", "us-west1"]
        if v not in valid_regions:
            raise ValueError(f"Region must be one of: {', '.join(valid_regions)}")
        return v

    @field_validator("scheduler_schedule")
    @classmethod
    def validate_cron(cls, v: str) -> str:
        """Validate cron expression format (basic check)."""
        parts = v.split()
        if len(parts) != 5:
            raise ValueError("Cron expression must have 5 fields (minute hour day month weekday)")
        return v

    @field_validator("billing_budget_limit_usd")
    @classmethod
    def validate_budget(cls, v: str) -> str:
        """Validate budget limit is a positive number."""
        try:
            float_val = float(v)
        except (ValueError, TypeError):
            raise ValueError("Budget must be a number")

        if float_val <= 0:
            raise ValueError("Budget must be positive")

        return v

    @classmethod
    def load_from_file(cls, path: str) -> "ZilchConfig":
        """Load configuration from .zilch.config file.

        Args:
            path: Path to config file

        Returns:
            ZilchConfig instance

        Raises:
            FileNotFoundError: If config file doesn't exist
            ValueError: If config is invalid
        """
        config_path = Path(path)
        if not config_path.exists():
            raise FileNotFoundError(f"Config file not found: {path}")

        with open(config_path) as f:
            content = f.read()

        # Prepend [DEFAULT] section for configparser to parse as key-value pairs
        config_content = "[DEFAULT]\n" + content

        parser = configparser.ConfigParser()
        parser.read_string(config_content)

        config_dict = dict(parser.defaults())

        try:
            return cls(**config_dict)
        except Exception as e:
            raise ValueError(f"Invalid config: {e}")

    def save_to_file(self, path: str) -> None:
        """Save configuration to .zilch.config file.

        Args:
            path: Path to config file
        """
        config_path = Path(path)
        config_path.parent.mkdir(parents=True, exist_ok=True)

        with open(config_path, "w") as f:
            f.write("# Zilch Reference App Configuration\n")
            f.write("# Auto-generated by zilch.py\n\n")

            f.write("# GitHub Integration (required for Cloud Build)\n")
            f.write(f'github_owner={self.github_owner or ""}\n')
            f.write(f'github_repo={self.github_repo or ""}\n\n')

            f.write("# GCP Settings\n")
            f.write(f"gcp_project_id={self.gcp_project_id}\n")
            f.write(f"app_name={self.app_name}\n")
            f.write(f"gcp_region={self.gcp_region}\n\n")

            f.write("# Phase 1 Optional Features\n")
            f.write(f"enable_firestore={str(self.enable_firestore).lower()}\n")
            f.write(f"enable_secret_manager={str(self.enable_secret_manager).lower()}\n")
            f.write(f"enable_cloud_storage={str(self.enable_cloud_storage).lower()}\n")
            f.write(f"enable_firebase_auth={str(self.enable_firebase_auth).lower()}\n")
            f.write(f"enable_vertex_ai={str(self.enable_vertex_ai).lower()}\n\n")

            f.write("# Phase 2: Cloud Build + GitOps (optional)\n")
            f.write(f"enable_cloud_build={str(self.enable_cloud_build).lower()}\n\n")

            f.write("# Phase 3: Advanced Services (optional)\n")
            f.write(f"enable_pubsub={str(self.enable_pubsub).lower()}\n")
            f.write(f"enable_cloud_tasks={str(self.enable_cloud_tasks).lower()}\n")
            f.write(f"enable_bigquery={str(self.enable_bigquery).lower()}\n")
            f.write(f"enable_cloud_kms={str(self.enable_cloud_kms).lower()}\n")
            f.write(f"enable_vision_ai={str(self.enable_vision_ai).lower()}\n")
            f.write(f"enable_speech_to_text={str(self.enable_speech_to_text).lower()}\n")
            f.write(f"enable_translation={str(self.enable_translation).lower()}\n\n")

            f.write("# Phase 4: Cloud Scheduler & Monitoring (optional)\n")
            f.write(f"enable_scheduler={str(self.enable_scheduler).lower()}\n")
            f.write(f"scheduler_schedule={self.scheduler_schedule}\n")
            f.write(f"scheduler_timezone={self.scheduler_timezone}\n")
            f.write(f"scheduler_endpoint={self.scheduler_endpoint}\n")
            f.write(f"enable_monitoring={str(self.enable_monitoring).lower()}\n")
            f.write(f"billing_account_name={self.billing_account_name}\n")
            f.write(f"billing_budget_limit_usd={self.billing_budget_limit_usd}\n\n")

            f.write("# Phase 5: MySQL Database (optional)\n")
            f.write(f"enable_mysql={str(self.enable_mysql).lower()}\n")
            f.write(f"mysql_database_name={self.mysql_database_name}\n\n")

            f.write("# Cloud Run Access Control & Billing\n")
            f.write(f"allow_unauthenticated_access={str(self.allow_unauthenticated_access).lower()}\n")
            f.write(f'gcp_billing_account_id={self.gcp_billing_account_id or ""}\n')

    def to_terraform_vars(self) -> dict:
        """Convert config to Terraform variables.

        Returns:
            Dictionary of terraform variables
        """
        return {
            "gcp_project_id": self.gcp_project_id,
            "app_name": self.app_name,
            "gcp_region": self.gcp_region,
            "github_owner": self.github_owner or "",
            "github_repo": self.github_repo or "",
            "enable_firestore": self.enable_firestore,
            "enable_secret_manager": self.enable_secret_manager,
            "enable_cloud_storage": self.enable_cloud_storage,
            "enable_firebase_auth": self.enable_firebase_auth,
            "enable_vertex_ai": self.enable_vertex_ai,
            "enable_cloud_build": self.enable_cloud_build,
            "enable_pubsub": self.enable_pubsub,
            "enable_cloud_tasks": self.enable_cloud_tasks,
            "enable_bigquery": self.enable_bigquery,
            "enable_cloud_kms": self.enable_cloud_kms,
            "enable_vision_ai": self.enable_vision_ai,
            "enable_speech_to_text": self.enable_speech_to_text,
            "enable_translation": self.enable_translation,
            "enable_scheduler": self.enable_scheduler,
            "scheduler_schedule": self.scheduler_schedule,
            "scheduler_timezone": self.scheduler_timezone,
            "scheduler_endpoint": self.scheduler_endpoint,
            "enable_monitoring": self.enable_monitoring,
            "billing_account_name": self.billing_account_name,
            "billing_budget_limit_usd": self.billing_budget_limit_usd,
            "enable_mysql": self.enable_mysql,
            "mysql_database_name": self.mysql_database_name,
            "allow_unauthenticated_access": self.allow_unauthenticated_access,
            "gcp_billing_account_id": self.gcp_billing_account_id or "",
        }

    def to_dict(self) -> dict:
        """Convert config to dictionary."""
        return self.model_dump()
